### ISSUE TITLE
Скрытие HUD

### ISSUE THREAD

**Issue by RblSb** [EXL/Gish#1]
Может сделать галочку на отключение рамки при игре, или вообще ее не грузить/ перерисовать только под фон для hp/времени/очков? Отрисовка тайлов ограничена по этой рамке или по размеру экрана?

**Comment by RblSb** [comment]
Временный вариант: скопировать файл из этого архива в Resources/texture/
[border.tga.zip](https://github.com/EXL/Gish/files/1065505/border.tga.zip) (белый пиксель с 0.1 прозрачности, полностью прозрачный не вышло сделать)
Правда в таком случае на нулевой y корде появляется два черных пикселя при игре на x: 1/3 и 2/3 экрана. Возможно не связаны с рамкой, хз.

**Comment by EXL** [comment]
> Может сделать галочку на отключение рамки при игре

@RblSb, я добавил опцию "Disable borders", коммиты 9523f9c и 71e7de6.

Промежуточный релиз Gish APK v1.1 с накопительными обновлениями:

- Исправлено зависание при выборе рендерера GL4ES на устройствах с Android OS < 4.0;
- Исправлен сброс настроек с формы при выходе из различных диалогов;
- Добавлен параметр, отключающий рамку.

Скачать: [Gish_v1.1_10-JUN-2017.apk.zip](https://github.com/EXL/Gish/files/1065585/Gish_v1.1_10-JUN-2017.zip)

Просьба скачать APK-пакет, разархивировать, установить и протестировать:

- Опцию отключения рамки;
- Запуск и работу игры на рендерере GL4ES.

И ещё, скажите пожалуйста, что у вас за модель смартфона? Спасибо.

**Comment by RblSb** [comment]
Все норм, спасибо. htc one m7. Как-то странно все-таки выглядит такое слабое фпс, даже на уровне с футболом с выключенным освещением 60 не держит, одна физика столько ест?

**Comment by EXL** [comment]
@RblSb имеется много факторов, которые снижают FPS в Gish'е. 

Во-первых, игрушка старая, 2004 года. Её создатели думали что большинство игроков будут играть в Gish'а в небольшом окне с разрешением 800x600. Поэтому для современных FullHD-дисплеев (вроде того, что у тебя на смартфоне), Gish оптимизирован довольно плохо.

Во-вторых, авторы Gish'а нисколько не задумывались об оптимизации, поскольку игра изначально создавалась под дискретные и сильные видеокарты. Поэтому нативная версия Gish'а под тот же MS Windows тормозит у меня на ноутбуке на интегрированном GPU Intel HD @ Intel i3 даже в окне.  

В-третьих, библиотека-прослойка SDL2 немного понижает FPS.

В-четвёртых, сенсорное управление на Java просто перекрывает экран игры сверху, что тоже немного влияет на FPS.

Все эти факторы складываются вместе и поэтому возникает такая слабая картина. Над третьем и четвёртым факторами ещё можно немного поработать, например, перенести сенсорное управление в нативный движок Gish'а или избавиться от SDL2. Это должно поднять немного FPS, но это довольно сложная и нудная работа. Если будет свободное время, займусь четвёртым фактором, если ты отключишь сенсорное управление в игре и попробуешь запустить тяжёлые уровни, то увидишь, что FPS повысится на 5-15 кадров.

Кстати, в оригинальной компьютерной версии Gish, почему-то FPS был специально немного занижен с помощью аналога _sleep()_, возможно, чтобы герой игры был более "вязким".

**Comment by RblSb** [comment]
@EXL печально, что по большей части ничего не исправить. В любом случае, спасибо за порт, играть очень удобно, в свободное время залипаю в кастомные кампании, потом еще и Cave Story посмотрю, давно думал. Удачи в новых проектах!

**Comment by EXL** [comment]
@RblSb спасибо за тёплые слова, постараюсь ещё что-нибудь когда-нибудь портировать.
