### ISSUE TITLE
Hello,Where can i get the ace.tga file? 

### ISSUE THREAD

**Issue by thirdparty-core** [EXL/Gish#3]
Hello,Where can i get the ace.tga file?

**Comment by EXL** [comment]
@lijiayan2015 Did you mean face.tga?

**Comment by thirdparty-core** [comment]
@EXL yes,i lost the f.
i am working for how to use the two funs:
```
Gint glRenderMode(GLenum mode);

void glSelectBuffer(GLsizei size, GLuint* buffer);
```
in my android pro in Opengl ES,but ES no impl the two funs and i don't know hao to deal with it,i search on github then find your Gish,i think may be your gish can help me,please.....   thk.


And my English is poor,^_^

**Comment by EXL** [comment]
@lijiayan2015 Please e-mail me about this file:

`exlmotodev <at> gmail <d0t> com`

>in my android pro in Opengl ES,but ES no impl the two funs and i don't know hao to deal with it

My fork does not use these functions, but this methods are implemented in [GL4ES](https://github.com/ptitSeb/gl4es) library. Just link this library to your project, as I did in the case of Gish.

**Comment by thirdparty-core** [comment]
thk!
