### ISSUE TITLE
Can't launch the game

### ISSUE THREAD

**Issue by Creeperface01** [EXL/Gish#4]
Hi I would like to test your port because I remeber when I played this game on my old Phone but unfortunately it won't launch but keeps saying something with the data directory. 

https://streamable.com/2ol8b

**Comment by EXL** [comment]
@Creeperface01 Hello! 
This port requires original data files from Gish game.
You can get it from [Steam](http://www.chroniclogic.com/gish.htm), [official site](http://www.chroniclogic.com/gish.htm) or any other ways :smiley_cat: 
When you receive it, unpack it to any place and select the Gish catalog as shown [here in the video](https://www.youtube.com/watch?v=GyMU2oV2LI4).

Enjoy!
